//variable

let btn = document.querySelector('#new-quote');
let quote = document.querySelector('.quote');
let person = document.querySelector('.person');

const quotes = [
  { quote: "Folks are usually about as happy as they make their minds up to be.", person: "Abraham Lincoln" },
  { quote: "The only way to do great work is to love what you do.", person: "Steve Jobs" },
  { quote: "In the end, we will remember not the words of our enemies, but the silence of our friends.", person: "Martin Luther King Jr." },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", person: "Winston Churchill" },
  { quote: "Happiness depends upon ourselves.", person: "Aristotle" },
  { quote: "Do what you can, with what you have, where you are.", person: "Theodore Roosevelt" },
  { quote: "It always seems impossible until it’s done.", person: "Nelson Mandela" },
  { quote: "Be yourself; everyone else is already taken.", person: "Oscar Wilde" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", person: "Eleanor Roosevelt" },
  { quote: "Don’t count the days, make the days count.", person: "Muhammad Ali" },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", person: "Zig Ziglar" },
  { quote: "Believe you can and you're halfway there.", person: "Theodore Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", person: "William James" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", person: "Walt Whitman" },
  { quote: "Opportunities don't happen, you create them.", person: "Chris Grosser" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", person: "George Addair" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", person: "C.S. Lewis" },
  { quote: "Turn your wounds into wisdom.", person: "Oprah Winfrey" },
  { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", person: "William Butler Yeats" },
  { quote: "The best way to predict the future is to invent it.", person: "Alan Kay" },
  { quote: "Dream big and dare to fail.", person: "Norman Vaughan" },
  { quote: "You miss 100% of the shots you don’t take.", person: "Wayne Gretzky" },
  { quote: "Strive not to be a success, but rather to be of value.", person: "Albert Einstein" },
  { quote: "I am not a product of my circumstances. I am a product of my decisions.", person: "Stephen R. Covey" },
  { quote: "An unexamined life is not worth living.", person: "Socrates" },
  { quote: "Your time is limited, so don’t waste it living someone else’s life.", person: "Steve Jobs" },
  { quote: "Winning isn’t everything, but wanting to win is.", person: "Vince Lombardi" },
  { quote: "Whether you think you can or you think you can’t, you’re right.", person: "Henry Ford" },
  { quote: "I have learned over the years that when one’s mind is made up, this diminishes fear.", person: "Rosa Parks" },
  { quote: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", person: "Mother Teresa" },
  { quote: "Nothing is impossible, the word itself says ‘I’m possible’!", person: "Audrey Hepburn" },
  { quote: "The question isn’t who is going to let me; it’s who is going to stop me.", person: "Ayn Rand" },
  { quote: "The only person you are destined to become is the person you decide to be.", person: "Ralph Waldo Emerson" },
  { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", person: "Henry David Thoreau" },
  { quote: "Life is what happens when you’re busy making other plans.", person: "John Lennon" },
  { quote: "The mind is everything. What you think you become.", person: "Buddha" },
  { quote: "The best revenge is massive success.", person: "Frank Sinatra" },
  { quote: "The journey of a thousand miles begins with one step.", person: "Lao Tzu" },
  { quote: "Fall seven times and stand up eight.", person: "Japanese Proverb" },
  { quote: "The secret of getting ahead is getting started.", person: "Mark Twain" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", person: "Sam Levenson" },
  { quote: "Keep your eyes on the stars, and your feet on the ground.", person: "Theodore Roosevelt" },
  { quote: "The harder I work, the luckier I get.", person: "Samuel Goldwyn" },
  { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", person: "Eleanor Roosevelt" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", person: "Ralph Waldo Emerson" },
  { quote: "If you want to lift yourself up, lift up someone else.", person: "Booker T. Washington" },
  { quote: "Limit your 'always' and your 'nevers'.", person: "Amy Poehler" },
  { quote: "Try to be a rainbow in someone’s cloud.", person: "Maya Angelou" },
  { quote: "You must be the change you wish to see in the world.", person: "Mahatma Gandhi" },
  { quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", person: "Mother Teresa" },
  { quote: "Don’t cry because it’s over, smile because it happened.", person: "Dr. Seuss" },
  { quote: "If opportunity doesn’t knock, build a door.", person: "Milton Berle" },
  { quote: "Do not let what you cannot do interfere with what you can do.", person: "John Wooden" },
  { quote: "Act as though it is impossible to fail.", person: "Dorothea Brande" },
  { quote: "Keep going. Be all in.", person: "Bryan Hutchinson" },
  { quote: "Don’t let yesterday take up too much of today.", person: "Will Rogers" },
  { quote: "Failure will never overtake me if my determination to succeed is strong enough.", person: "Og Mandino" },
  { quote: "We may encounter many defeats but we must not be defeated.", person: "Maya Angelou" },
  { quote: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", person: "Johann Wolfgang von Goethe" },
  { quote: "The way to get started is to quit talking and begin doing.", person: "Walt Disney" },
  { quote: "Don’t let the fear of losing be greater than the excitement of winning.", person: "Robert Kiyosaki" },
  { quote: "If you really look closely, most overnight successes took a long time.", person: "Steve Jobs" },
  { quote: "The man who has confidence in himself gains the confidence of others.", person: "Hasidic Proverb" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", person: "Franklin D. Roosevelt" },
  { quote: "Creativity is intelligence having fun.", person: "Albert Einstein" },
  { quote: "Do one thing every day that scares you.", person: "Eleanor Roosevelt" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", person: "Ralph Waldo Emerson" },
  { quote: "The best dreams happen when you’re awake.", person: "Cherie Gilderbloom" },
  { quote: "Don’t wait. The time will never be just right.", person: "Napoleon Hill" },
  { quote: "If you can dream it, you can do it.", person: "Walt Disney" },
  { quote: "Do not pray for easy lives. Pray to be stronger men.", person: "John F. Kennedy" },
  { quote: "A person who never made a mistake never tried anything new.", person: "Albert Einstein" },
  { quote: "The only way to achieve the impossible is to believe it is possible.", person: "Charles Kingsleigh" },
  { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", person: "Roy T. Bennett" },
  { quote: "The purpose of our lives is to be happy.", person: "Dalai Lama" },
];

btn.addEventListener('click', () => {
  let random = Math.floor(Math.random() * quotes.length);

  quote.innerText = quotes[random].quote;
  person.innerText = quotes[random].person;
})